### ISSUE TITLE
Runtime error in torchfold.py file

### ISSUE THREAD

**Issue by supriya-gdptl** [yzhou359/3DIndoor-SceneGraphNet#3]
Hello @yzhou359,

Thank you for sharing the code and data.

I am trying to train the SceneGraphNet model by running the command you have given on the GitHub page. I am using the 'torchfold.py' file that you have shared. Still, I got the following error after training for a few hours:

`
TRAIN JOB_NAME 6 : (3033/5000:11.0) CAT Loss: 2.8641, Acc_1: 1.0000, Acc_3: 1.0000, Acc_5: 1.0000,Dim Loss: 96.30447665, dim acc: 1.00`

`Traceback (most recent call last):`
`File "main.py", line 61, in <module>`

`File "/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 481, in train`
    `self._training_pass(self.valid_rooms_train, epoch, is_training=True)`
  
  `File "/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 306, in _training_pass`
    `rand_path_fold, rand_path_node_name_order = self.model.encode_tree_fold(enc_fold, sub_node_list, rand_path, opt_parser)`
  
  `File "/3DIndoor-SceneGraphNet/SceneGraphNet/model.py", line 415, in encode_tree_fold`
    `encode_node(node_list, leaf_node=tree_leaf_node, step=i)`

`File "/3DIndoor-SceneGraphNet/SceneGraphNet/model.py", line 334, in encode_node `  
      `to_torch(dis_feat))`

`File "/torchfold/torchfold.py", line 96, in add`
 `if args not in self.cached_nodes[op]:`

`RuntimeError: bool value of Tensor with more than one value is ambiguous
`

Could you please help me resolve this error?

Thank you,
Supriya

**Comment by supriya-gdptl** [comment]
It looks like this is a problem with 'torchfold' alone and has nothing to do with SceneGraphNet code. The issue was already raised in nearai/torchfold#8.

@yzhou359 Would it be possible to provide a version of SceneGraphNet code that does not use TorchFold? It will be really helpful.

Thanks

**Comment by yzhou359** [comment]
Thanks for pointing this out and inquire the torchfold author! You can try the way they suggest. What we did is to retrain the model to avoid this problem. 
I'm sorry currently we have no plan to improve this repo with other GCN packages.
