### ISSUE TITLE
GPU Usage & Training Speed & TorchFold

### ISSUE THREAD

**Issue by czha5168** [yzhou359/3DIndoor-SceneGraphNet#6]
Hi Yang,

Thanks for providing the well-written code, which I learnt a lot from. Just would like to make an enquiry about the gpu memory usage & training speed from your side, as I noticed 0 gpu memory consumed (are they running in cpu???) in my machine (with slow training speed). Could you please give me your confirmation on whether this is a normal case caused by TorchFold? Thanks in advance!

**Comment by yzhou359** [comment]
It should use GPU by default. But it does take a long time to train as it uses the TorchFold package (you're right).
You can try advanced GCN packages with customized edge conv function to solve this problem e.g. https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html
