### ISSUE TITLE
Definition of Neighborhood in Co-Occurence Relationship

### ISSUE THREAD

**Issue by fcr3** [yzhou359/3DIndoor-SceneGraphNet#7]
In the data_structure readme, this is the definition of co-occurence:

```
co-occurrence list : a list of node's ids which are in neighbor of this node, especially for root and wall nodes (notice that this is not the next-to relation mentioned in the paper)
```

What is the definition of neighborhood? I thought that co-occurence is defined as objects co-occurring in a scene with a reference object in the same scene. However, based on the diagram in the readme, the walls are chosen to be connected to a subset of objects. 

How do we replicate this structure if we are working with other datasets?

**Comment by yzhou359** [comment]
Sorry for the confusion. As said in the description, this relationship is specifically for the `root` and `wall` nodes ONLY, which is used for create a connected graph structure originated from the virtual root and 4 walls. For each of the object, we find a nearest wall and connect the object with this relation to it. The wall node neighborhood is defined as the group of objects which are closest to it.
The actually co-occurence relation you mentioned is implemented [here](https://github.com/yzhou359/3DIndoor-SceneGraphNet/blob/ef80e201da6c57cbbd7a2b7f3121971ac32757a6/SceneGraphNet/model.py#L376) - defined as every pair of nodes co-occured in the same scene, which is also the loose connection mentioned in the paper.
