### ISSUE TITLE
Recursion error in Training Code

### ISSUE THREAD

**Issue by fcr3** [yzhou359/3DIndoor-SceneGraphNet#8]
Here is the sample data we use.
[bedroom_data.zip](https://github.com/yzhou359/3DIndoor-SceneGraphNet/files/5293847/bedroom_data.zip)

This is the command I run.

```
python main.py --name matterport_train --train_cat --room_type bedroom --num_train_rooms 200 --num_test_rooms 22
```

I'm getting the following error. 

```
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    M.train(epoch)
  File "/home/fcr/research/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 481, in train
    self._training_pass(self.valid_rooms_train, epoch, is_training=True)
  File "/home/fcr/research/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 280, in _training_pass
    subtree_to_leaf_path = self.find_root_to_leaf_node_path(node_list, cur_node=sub_tree_root_node)
  File "/home/fcr/research/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 103, in find_root_to_leaf_node_path
    child_node_list = self.find_root_to_leaf_node_path(node_list, child)
  File "/home/fcr/research/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 103, in find_root_to_leaf_node_path
    child_node_list = self.find_root_to_leaf_node_path(node_list, child)
  File "/home/fcr/research/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 108, in find_root_to_leaf_node_path
    child_node_list = self.find_root_to_leaf_node_path(node_list, key)
  File "/home/fcr/research/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 108, in find_root_to_leaf_node_path
    child_node_list = self.find_root_to_leaf_node_path(node_list, key)
  File "/home/fcr/research/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 108, in find_root_to_leaf_node_path
    child_node_list = self.find_root_to_leaf_node_path(node_list, key)
  [Previous line repeated 991 more times]
  File "/home/fcr/research/3DIndoor-SceneGraphNet/SceneGraphNet/train.py", line 97, in find_root_to_leaf_node_path
    len(node_list[cur_node]['support']) > 0):
RecursionError: maximum recursion depth exceeded in comparison
```

Can you help me debug this issue? I'm not sure what's wrong. I followed the instructions on the data_structurees.md document, but maybe there are things that don't line up.

**Comment by fcr3** [comment]
In the paper, there was mention of non-convergence. The paper states, "Our message passing update scheme is not guaranteed to converge, nor we forced it to be a contraction map. Oscillations can happen as in other message passing algorithms e.g., loopy belief propagation. Training and testing with the same number of iterations helps preventing unstable behavior."  

From my point of view, I thought that non-convergence means that you don't really achieve a minimum that would give you the best predictions. But does non-convergence imply a max recursion error in our code?

**Comment by fcr3** [comment]
Another question I have is about the definition of valid_rooms. I couldn't find it in the paper or in the data readme.

**Comment by yzhou359** [comment]
> Another question I have is about the definition of valid_rooms. I couldn't find it in the paper or in the data readme.

`valid_rooms` is just the unified name for rooms used for both train/test time. We named it as all the rooms are preprocessed through our pre-cleaning code.

**Comment by yzhou359** [comment]
> In the paper, there was mention of non-convergence. The paper states, "Our message passing update scheme is not guaranteed to converge, nor we forced it to be a contraction map. Oscillations can happen as in other message passing algorithms e.g., loopy belief propagation. Training and testing with the same number of iterations helps preventing unstable behavior."
> 
> From my point of view, I thought that non-convergence means that you don't really achieve a minimum that would give you the best predictions. But does non-convergence imply a max recursion error in our code?



> In the paper, there was mention of non-convergence. The paper states, "Our message passing update scheme is not guaranteed to converge, nor we forced it to be a contraction map. Oscillations can happen as in other message passing algorithms e.g., loopy belief propagation. Training and testing with the same number of iterations helps preventing unstable behavior."
> 
> From my point of view, I thought that non-convergence means that you don't really achieve a minimum that would give you the best predictions. But does non-convergence imply a max recursion error in our code?

I think the error is not because of the non-convergence, but due to a loop relation. My code propogates in a DFS manner on a tree structure with `support` and `surround` relation, which may not create loops. You may need to clear the loop in your dataset, or stop the DFS by checking wether the node is visited.
