### ISSUE TITLE
Iterative Scene Synthesis Scripts

### ISSUE THREAD

**Issue by fcr3** [yzhou359/3DIndoor-SceneGraphNet#9]
I was just wondering if you have code to support iterative scene synthesis. Do you just create a bunch of trees which represent points of the room and do multiple inferences on that? Is there a clearer approach that can just take in an input spot, given a scene?

**Comment by yzhou359** [comment]
Thanks for your interest. Unfortunately, we don't provide such script. As you said, it would be a script interatively calling the current inference on the previous room stage. You may need to modify the current dataloader and test script a bit to achieve that.
